/**
 * The `--help` text. It documents the exit codes because the CLI is driven by
 * an agent through a bash tool, and the exit code is the only signal that
 * survives without parsing output.
 */
import {
  ATOM_TYPES,
  DEFAULT_EXCLUDED_TYPES,
  DEFAULT_RERANK_PRESET,
  REPHRASE_MODEL_ENV_VAR,
  REPHRASE_MODEL_ID,
  RERANK_DEFAULT_URL,
  RERANK_K_INIT,
  RERANK_MODEL_ID,
  RERANK_PRESET_NAMES,
  RERANK_URL_ENV_VAR,
  RETRIEVE_TOKEN_BUDGET
} from '../config.js';
import { ADAPTER_NAMES, DEFAULT_ADAPTER } from './adapter.js';
import { flagList } from './args.js';
import { OUTPUT_FORMATS } from './format.js';

export const HELP_TEXT: string = [
  'dp-gnosis — retrieval over a curated markdown atom vault',
  '',
  'Usage: dp-gnosis <command> [args] [flags]',
  '',
  'Commands:',
  '  ingest             chunk the configured corpus roots into atom files',
  '  index              build the selected adapter index (no-op where none exists)',
  '  retrieve <query>   rank atoms for a query',
  '  bench              measure every adapter over the golden set; writes a report to docs/test/',
  '',
  `Flags: ${flagList()}`,
  `Output: --format ${OUTPUT_FORMATS.join('|')} on \`retrieve\` only (default text); --json means \`--format json\``,
  '  xml emits a <retrieved_context> block carrying each atom body — paste-ready for an LLM',
  '  passing --json together with --format xml is a usage error; another command with --format is too',
  `Types: --type <type[,type]> on \`retrieve\` only — an atom passes when its type is in the list; omit it to search every type`,
  `  vocabulary: ${ATOM_TYPES.join(' | ')}`,
  `  the CLI path only — never ingest, never the bench — leaves ${DEFAULT_EXCLUDED_TYPES.join(' | ')} out of an unfiltered retrieve, so a question is answered from knowledge rather than from the project's own history`,
  `  --exclude-type <type[,type]> REPLACES that default exclusion with the types you name; --include-history restores everything and searches the whole vocabulary`,
  `  --type, --exclude-type and --include-history each state the filter in a different way, so pass at most one — two together is a usage error (exit 2)`,
  `Budget: --max-tokens <n> on \`retrieve\` only (default ${RETRIEVE_TOKEN_BUDGET}) — a CONSERVATIVE UPPER BOUND on tokens, estimated as UTF-8 byte length, never an exact token count`,
  `  it over-reserves: measured 2026-08-18, real atoms run 3.93 bytes/token, so the ${RETRIEVE_TOKEN_BUDGET} default admits roughly 16000 real tokens — size the flag ~4x the window you mean to fill`,
  '  an atom over the remaining budget is SKIPPED and the walk continues; every skip is reported with its id, source path and estimated size',
  `Rerank: --rerank on \`retrieve\` only, OFF by default — reranks a pool of at least ${RERANK_K_INIT} with ${RERANK_MODEL_ID} and RRF-fuses that order with the first pass, then applies the budget`,
  `  the pool is a FLOOR, not a cap: a larger -k reranks its own depth. It is the measured champion depth and costs roughly 12s per query`,
  `  the endpoint is a llama-swap OpenAI-compatible server at ${RERANK_DEFAULT_URL}, overridable with ${RERANK_URL_ENV_VAR}`,
  '  a refused rerank still returns the FIRST-PASS ranking, but exits 3 with the refusal in note and mode keeping no +rerank suffix',
  '  it is refused by an unreachable server, one not serving that model, or one failing the two-document discrimination probe — never silently unreranked',
  `  --rerank-model <id> scores with another cross-encoder; --rerank-profile ${RERANK_PRESET_NAMES.join('|')} selects the fusion rule (default ${DEFAULT_RERANK_PRESET}); --rerank-weight <w> overrides the reranked order's RRF weight, 0 to 1, never clamped`,
  '  all three require --rerank and are a usage error (exit 2) without it — nothing would rerank, yet the result would carry the label',
  `Rephrase: --rephrase on \`retrieve\` only, OFF by default — rewrites the question into a BM25 keyword query with ${REPHRASE_MODEL_ID} (override with ${REPHRASE_MODEL_ENV_VAR}) before the first pass, then searches the rewrite`,
  '  the rewrite is cached on disk beside the index, so a repeated query costs no network; the reported query stays the one you typed, with the rewrite beside it as queryRewritten',
  '  a refused rewrite still retrieves with the query AS TYPED, but exits 3 with the refusal in note — a skipped rewrite never reports as a rephrased run',
  'Profile: --profile <file> selects one named instance — its vocabulary, its labelling tables and its own repoRoot, corpusRoots, atomsDir and indexPath',
  '  precedence is flag > profile > default, so --atoms-dir / --index-path / --repo-root still override whatever the profile states',
  '  each profile MUST own its atomsDir AND its indexPath: an atoms directory is stamped with its owner and refuses a second profile',
  `Adapters: ${ADAPTER_NAMES.join(' | ')} (default ${DEFAULT_ADAPTER}, the measured champion and what the bench measures); the adapter changes ranking and speed only`,
  `  ${DEFAULT_ADAPTER} searches an INDEX: a corpus that was ingested but never indexed reports indexState unavailable (exit 3) with the build command in its note`,
  '  minisearch and lancedb are optional dependencies — an absent one is reported, never hidden',
  '',
  'Exit codes:',
  '  exit 0  success',
  '  exit 2  bad input or usage; the message names the correction',
  '  exit 3  partial result — some work succeeded and some was refused (e.g. ingest skips,',
  '          bench ran with an adapter skipped, or index found the adapter\'s optional',
  '          dependency absent so nothing was built)',
  '',
  'JSON keys with --json (plus exitCode on every object):',
  '  ingest    command, written, skipped[{source,title,reasons}]',
  '  index     command, adapter, built, indexPath, note',
  '  retrieve  command, adapter, query, queryRewritten (with --rephrase only), k, mode, indexState, count, poolSize (first-pass size, before -k),',
  '            atoms[{id,title,domain,body,score,firstPassScore + rerankScore (with --rerank only),sourcePath,originPaths[],matchedTerms[],snippet,scoreNormalised}],',
  '            skipped[{id,sourcePath,estimatedTokens}], note',
  '  bench     command, markdownPath, jsonPath, adapters[], skippedAdapters[{name,reason}], corpora[], goldenSet',
  '  failure   error',
].join('\n');
