/**
 * The `--help` text. It documents the exit codes because the CLI is driven by
 * an agent through a bash tool, and the exit code is the only signal that
 * survives without parsing output.
 */
import {
  DEFAULT_RERANK_PRESET,
  ENRICH_MODEL_ENV_VAR,
  ENRICH_MODEL_ID,
  FTS_COLUMNS,
  REPHRASE_MODEL_ENV_VAR,
  REPHRASE_MODEL_ID,
  RERANK_DEFAULT_URL,
  RERANK_K_INIT,
  RERANK_MODEL_ENV_VAR,
  RERANK_MODEL_ID,
  RERANK_PRESET_NAMES,
  RERANK_URL_ENV_VAR,
  RETRIEVE_TOKEN_BUDGET,
  SYNTHESIZE_MODEL_ENV_VAR,
  SYNTHESIZE_MODEL_ID
} from '../config.js';
import { DEFAULT_PRF_PARAMS, SERVED_PRF_PARAMS } from '../prf.js';
import { USER_CONFIG_FILE } from '../userConfig.js';
import { atomDomains, atomTypes, defaultExcludedTypes } from '../vocabulary.js';
import { ADAPTER_NAMES, DEFAULT_ADAPTER } from './adapter.js';
import { flagList } from './args.js';
import { OUTPUT_FORMATS } from './format.js';
import { DEFAULT_MAX_PER_DOC } from './grouping.js';
import { SETUP_COMMAND } from './setupCommand.js';

/**
 * A FUNCTION, not a constant: three of the lines below print the ACTIVE
 * profile's vocabulary, and a module-level constant would resolve that profile
 * the moment anything imported this file. The rendered text is unchanged.
 */
export const helpText = (): string => [
  'dp-gnosis — retrieval over a curated markdown atom vault',
  '',
  'Usage: dp-gnosis <command> [args] [flags]',
  '',
  'Commands:',
  '  init <dir> [dir…] create this machine\'s instance: the data directories, an editable profile and the owner marker',
  '  wizard             the guided first run — asks what to index, how to rank it, whether to rerank, then builds it and proves it answers',
  '  setup              probe this machine for a WORKING reranker and write the one that passes into config.json — no server, no vault and no instance needed',
  '  demo               ingest and search this tool\'s OWN documentation in a fixed demo/ subtree — no corpus needed, your vault untouched',
  '  doctor             report the resolved locations, the index stamps and every silent precedence loss — READ-ONLY, repairs nothing',
  '  ingest             chunk the configured corpus roots into atom files',
  '  enrich             generate the enrichment sidecar for those atoms (one model call per atom)',
  '  index              build the selected adapter index (no-op where none exists)',
  '  update             ingest then index in one command — the pair that MUST NOT be split; it exits with the more severe of the two, so an ingest that skipped files still exits 3',
  '  search <query>     rank atoms for a query',
  '  ask <query>        the same ranking, rendered as one citable knowledge pack',
  '  bench              measure every adapter over the golden set; writes a report to docs/test/',
  '',
  `Flags: ${flagList()}`,
  `Output: --format ${OUTPUT_FORMATS.join('|')} on \`search\` and \`ask\` (default text; \`ask\` takes text or json, never xml); --json means \`--format json\``,
  '  xml emits a <retrieved_context> block carrying each atom body — paste-ready for an LLM',
  '  passing --json together with --format xml is a usage error; another command with --format is too',
  `Types: --type <type[,type]> on \`search\` and \`ask\` — an atom passes when its type is in the list; omit it to search every type`,
  `  vocabulary: ${atomTypes().join(' | ')}`,
  `  it is a RETRIEVE-TIME default — applied on the CLI path, and by the bench when it derives the vault datasets, never on ingest — leaving ${defaultExcludedTypes().join(' | ')} out of an unfiltered retrieve, so a question is answered from knowledge rather than from the project's own history; the types stay ingested and indexed`,
  `  --exclude-type <type[,type]> REPLACES that default exclusion with the types you name; --include-history restores everything and searches the whole vocabulary`,
  `  --type, --exclude-type and --include-history each state the filter in a different way, so pass at most one — two together is a usage error (exit 2)`,
  `Domains: --domain <domain[,domain]> on \`search\` and \`ask\` — an atom passes when its domain is in the list; omit it to search every domain`,
  `  vocabulary: ${atomDomains().join(' | ')}`,
  `  it is the LOADED profile's vocabulary, so --profile <file> selects a different one and a value outside it is a usage error (exit 2)`,
  `Budget: --max-tokens <n> on \`search\` and \`ask\` (default ${RETRIEVE_TOKEN_BUDGET}) — a CONSERVATIVE UPPER BOUND on tokens, estimated as UTF-8 byte length, never an exact token count`,
  `  it over-reserves: measured 2026-08-18, real atoms run 3.93 bytes/token, so the ${RETRIEVE_TOKEN_BUDGET} default admits roughly 16000 real tokens — size the flag ~4x the window you mean to fill`,
  '  an atom over the remaining budget is SKIPPED and the walk continues; every skip is reported with its id, source path and estimated size',
  `Rerank: --rerank on \`search\` and \`ask\`, OFF by default — reranks a pool of at least ${RERANK_K_INIT} with ${RERANK_MODEL_ID} and RRF-fuses that order with the first pass, then applies the budget`,
  `  the pool is a FLOOR, not a cap: a larger -k reranks its own depth. It is the measured champion depth and costs roughly 12s per query`,
  `  the endpoint is a llama-swap OpenAI-compatible server at ${RERANK_DEFAULT_URL} serving ${RERANK_MODEL_ID}; both are overridable, but NO flag states the URL — it resolves environment (${RERANK_URL_ENV_VAR}) > ${USER_CONFIG_FILE} ("rerank": {"url"}) > the shipped constant`,
  `  the model resolves --rerank-model > environment (${RERANK_MODEL_ENV_VAR}) > ${USER_CONFIG_FILE} ("rerank": {"model"}) > the shipped constant`,
  `  \`${SETUP_COMMAND}\` writes that ${USER_CONFIG_FILE} block for you — it finds the server, probes only the ids whose name says reranker, and writes the first that PASSES the discrimination probe`,
  '  a refused rerank still returns the FIRST-PASS ranking, but exits 3 with the refusal in note and mode keeping no +rerank suffix',
  '  it is refused by an unreachable server, one not serving that model, or one failing the two-document discrimination probe — never silently unreranked',
  `  --rerank-model <id> scores with another cross-encoder; --rerank-profile ${RERANK_PRESET_NAMES.join('|')} selects the fusion rule (default ${DEFAULT_RERANK_PRESET}); --rerank-weight <w> overrides the reranked order's RRF weight, 0 to 1, never clamped`,
  `  --rerank-pool <n> reranks n candidates instead of the shipped ${RERANK_K_INIT}, whole number of at least 1, never rounded — a profile states the same depth as "rerankPoolK", and the flag outranks it`,
  '  all four require --rerank and are a usage error (exit 2) without it — nothing would rerank, yet the result would carry the label',
  'Relevance: --min-relevance <p> on `search` and `ask`, OFF by default — drops every delivered atom whose CALIBRATED relevance probability is below p, reporting how many fell below which floor',
  '  strictly subtractive: it never reorders, never promotes an atom from deeper in the pool and never moves poolSize; it requires --rerank and a reranker with a measured score scale, and refuses rather than clamping',
  `Rephrase: --rephrase on \`search\` and \`ask\`, OFF by default — rewrites the question into a BM25 keyword query with ${REPHRASE_MODEL_ID} (override with ${REPHRASE_MODEL_ENV_VAR}) before the first pass, then searches the rewrite`,
  '  the rewrite is cached on disk beside the index, so a repeated query costs no network; the reported query stays the one you typed, with the rewrite beside it as queryRewritten',
  '  a refused rewrite still retrieves with the query AS TYPED, but exits 3 with the refusal in note — a skipped rewrite never reports as a rephrased run',
  `Feedback: --prf on \`search\` and \`ask\` — RM3 pseudo-relevance feedback: the top --prf-docs atoms of the first pass build a weighted term model and the ranking is rescored with it. The shipped profiles SERVE it at fbDocs ${SERVED_PRF_PARAMS.fbDocs} / fbTerms ${SERVED_PRF_PARAMS.fbTerms} / alpha ${SERVED_PRF_PARAMS.alpha}; --no-prf turns that default off`,
  `  --prf-docs <n> how many atoms feed the model; --prf-terms <n> how many expansion terms survive; --prf-alpha <a> the expansion's share of the mass, 0 to 1, never clamped — each overrides ONE member of the served cell, falling back to ${DEFAULT_PRF_PARAMS.fbDocs}/${DEFAULT_PRF_PARAMS.fbTerms}/${DEFAULT_PRF_PARAMS.alpha} when the profile states none`,
  '  resolution is flag > profile default > OFF; --prf beside --no-prf is a usage error (exit 2), and so is a tuning flag with no feedback pass to tune',
  `  --prf is a usage error on any adapter but ${DEFAULT_ADAPTER} — it rides that scorer's own bm25(); a PROFILE default there retrieves UNEXPANDED and says so in note, because refusing would make every other adapter unusable`,
  `Grouping: --max-per-doc <n> on \`search\` and \`ask\` (default ${DEFAULT_MAX_PER_DOC}) — atoms of one source document are delivered together in reading order, marked (i/n), and no document contributes more than n`,
  '  the cap applies to the POOL before the -k slice, so a dropped atom frees a slot a lower-ranked document takes; --max-per-doc 0 caps nothing',
  '  --flat delivers the ranking ungrouped — no cap, no arrangement, no marker — and is a usage error (exit 2) beside --max-per-doc, which would then have nothing to cap',
  'Ask: ask runs the SAME pipeline as search — same flags, same ranking, same exit codes — and renders it as one delimited knowledge pack',
  '  the block carries each atom body under its source document with a [^atom-id] footnote to cite, and reports confidence, documents, atoms and tokens in its footer',
  '  every chat-template marker found in the corpus text is wrapped as [[neutralised:...]] and counted, so retrieved text cannot end the block or speak as the operator',
  '  the pack chrome is reserved from --max-tokens before the fit, so the ceiling bounds the whole block; --flat and --format xml are usage errors (exit 2) — the pack is grouped and delimited by construction',
  `Synthesize: --synthesize on \`ask\` only, OFF by default — answers the question over the pack with ${SYNTHESIZE_MODEL_ID} (override with ${SYNTHESIZE_MODEL_ENV_VAR}) and prints it ABOVE the pack, which follows unchanged as the evidence`,
  '  the model answers ONLY from the pack and cites every claim with the [^atom-id] it came from; INSUFFICIENT is an allowed answer and means the pack does not hold one',
  '  a citation the pack does not contain DISCARDS the whole answer — it is shown nowhere, the offending ids are named in note, and the run exits 3 with the pack alone',
  '  a refused synthesis (server down, model not served, call failed, empty content) behaves the same way: the pack is delivered, the refusal is in note, exit 3',
  `Enrich: enrich calls ${ENRICH_MODEL_ID} once per atom (override with ${ENRICH_MODEL_ENV_VAR} or --enrich-model <id>) and APPENDS one JSON line per atom to a sidecar`,
  '  --enrichment <file> names that sidecar (default enrichment.jsonl beside the atoms directory); --limit <n> enriches at most n not-yet-fresh atoms, for a pilot batch',
  '  it is RESUMABLE and sequential: an atom already fresh for this body, prompt version and model is skipped without a call, and the file is only ever appended to',
  '  a refused or schema-invalid answer STOPS the run with the message and exits 3; no partial record is written, so a re-run retries exactly that atom',
  '  ingest never calls a model, and index builds with an ABSENT sidecar exactly as before — enrichment is strictly additive',
  `Weights: --field-weights <col=w[,col=w]> on \`search\` and \`ask\` — BM25F column weights over ${FTS_COLUMNS.join(' | ')}, stated as OVERRIDES over the shipped defaults`,
  '  an unnamed column keeps its default, so --field-weights questions=2 leaves body at 1; an unknown column name is a usage error (exit 2) listing the vocabulary',
  '  the enrichment columns are populated only by an `index --enrichment <file>` build; without one they are empty and the ranking is what it has always been',
  'Profile: --profile <file> selects one named instance — its vocabulary, its labelling tables and its own repoRoot, corpusRoots, atomsDir and indexPath',
  '  precedence is flag > profile > default, so --atoms-dir / --index-path / --repo-root still override whatever the profile states',
  '  each profile MUST own its atomsDir AND its indexPath: an atoms directory is stamped with its owner and refuses a second profile',
  `Adapters: ${ADAPTER_NAMES.join(' | ')} (default ${DEFAULT_ADAPTER}, the measured champion and what the bench measures); the adapter changes ranking and speed only`,
  `  ${DEFAULT_ADAPTER} searches an INDEX: a corpus that was ingested but never indexed reports indexState unavailable (exit 3) with the build command in its note`,
  '  minisearch and lancedb are optional dependencies — an absent one is reported, never hidden',
  '',
  'Exit codes:',
  '  exit 0  success',
  '  exit 2  bad input or usage; the message names the correction',
  '  exit 3  partial result — some work succeeded and some was refused (e.g. ingest skips,',
  '          bench ran with an adapter skipped, or index found the adapter\'s optional',
  '          dependency absent so nothing was built)',
  '',
  'JSON keys with --json (plus exitCode on every object):',
  '  init      command, profilePath, atomsDir, indexPath, corpusRoots[], next[]',
  '  wizard    command, profilePath, indexState (or error + steps[{step,exitCode}] when a build step failed)',
  '  setup     command, url, model, configPath, replaced, probed[{model,kind,detail|relevantScore,irrelevantScore}], skipped[{id,why}] (over-cap rerankers, itemised), skippedSummary (the counted rest)',
  '  doctor    command, faults, warnings, checks[{name,status,detail}]',
  '  ingest    command, written, skipped[{source,title,reasons}]',
  '  enrich    command, model, promptVersion, atoms, enriched, skipped, sidecar, note (only on a refusal)',
  '  index     command, adapter, built, indexPath, note',
  '  update    command, ingest (the ingest payload), index (the index payload, null when ingest refused the invocation)',
  '  demo      command, query, corpus[], atomsDir, indexPath, ingest, index, search (each hop\'s own payload)',
  '  search    command, adapter, query, queryRewritten (with --rephrase only), k, mode, indexState, count, poolSize (first-pass size, before -k), budgetMode, confidence (none|weak|ok),',
  '            atoms[{id,title,domain,body,score,firstPassScore + rerankScore (with --rerank only),sourcePath,originPaths[],matchedTerms[],snippet,scoreNormalised}],',
  '            skipped[{id,sourcePath,estimatedTokens}], note',
  '  ask       command, adapter, query, queryRewritten (with --rephrase only), k, mode, indexState, count, documents, poolSize, budgetMode, maxTokens, packTokens, confidence,',
  '            pack (the whole block), citations[], atoms[] (as search), skipped[], neutralised, synthesized + answer (with --synthesize only; answer is null when none was rendered), note',
  '  bench     command, markdownPath, jsonPath, adapters[], skippedAdapters[{name,reason}], corpora[], goldenSet',
  '  failure   error',
].join('\n');
